### * Description

# This script fills a section "Others" in the Reference page of the website
# generated by pkgdown.

# The code was modified from:
# https://stackoverflow.com/questions/45886789/include-all-other-functions-in-a-pkgdown-reference-yaml

### * Run

updateYaml = function(mypkg, overwrite = FALSE) {
    require(yaml)
    currYaml = yaml::yaml.load_file("_pkgdown.yml")
    currRef = currYaml[["reference"]]
    currFuncs = unlist(lapply(currRef, function(x) (x$contents)))
    currFuncs = gsub("`", "", currFuncs)
    allPkgFuncs = ls(paste0("package:", mypkg))
    missingFuncs = setdiff(allPkgFuncs, currFuncs)
    if (length(missingFuncs) == 0) {
        message("All functions are already in _pkgdown.yml")
    } else {
        titles = unlist(lapply(currRef, function(x) (x$title)))
        othersSection = which(titles == "Others")
        if (length(othersSection) > 0) {
            # "Others" section already exists
            currRef[[othersSection]] = list(
                title = "Others",
                desc = "Other functions",
                contents = c(currRef[[othersSection]]$contents,
                             paste0("`", missingFuncs, "`"))
            )
        } else {
            # Create "Others" section and add it
            currRef[[length(currRef) + 1]] = list(
                title = "Miscellaneous",
                desc = "Functions not sorted in the previous categories.",
                contents = paste0("`", missingFuncs, "`"))
        }
        currYaml[["reference"]] = currRef
        if (overwrite) {
            write(as.yaml(currYaml), "_pkgdown.yml")
        } else {
            write(as.yaml(currYaml), "_pkgdown.new.yml")
        }
    }
}

library(isotracer)
updateYaml("isotracer", overwrite = TRUE)
